apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-workload-identity-config
data:
  AZURE_STORAGE_ACCOUNT_NAME: "<storage-account-name>"
  AZURE_STORAGE_ACCOUNT_URL: "https://<storage-account-name>.blob.core.windows.net/"
  AZURE_CLIENT_ID: "<azure-client-id>"
  AZURE_TENANT_ID: "<azure-tenant-id>"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-workload-identity
  annotations:
    azure.workload.identity/client-id: "<azure-client-id>"
    azure.workload.identity/tenant-id: "<azure-tenant-id>"
