apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
spec:
  labels:
    azure.workload.identity/use: "true"
  podTemplate:
    serviceAccountName: azure-workload-identity
  containerTemplate:
    env:
      - name: AZURE_STORAGE_ACCOUNT_NAME
        valueFrom:
          configMapKeyRef:
            name: azure-workload-identity-config
            key: AZURE_STORAGE_ACCOUNT_NAME
      - name: AZURE_STORAGE_ACCOUNT_URL
        valueFrom:
          configMapKeyRef:
            name: azure-workload-identity-config
            key: AZURE_STORAGE_ACCOUNT_URL
      - name: AZURE_CLIENT_ID
        valueFrom:
          configMapKeyRef:
            name: azure-workload-identity-config
            key: AZURE_CLIENT_ID
      - name: AZURE_TENANT_ID
        valueFrom:
          configMapKeyRef:
            name: azure-workload-identity-config
            key: AZURE_TENANT_ID
      - name: AZURE_FEDERATED_TOKEN_FILE
        value: /var/run/secrets/azure/tokens/azure-identity-token
