apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: azure-workload-identity
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.152.0
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                configMapKeyRef:
                  name: azure-workload-identity-config
                  key: AZURE_STORAGE_ACCOUNT_NAME
            - name: AZURE_STORAGE_ACCOUNT_URL
              valueFrom:
                configMapKeyRef:
                  name: azure-workload-identity-config
                  key: AZURE_STORAGE_ACCOUNT_URL
            - name: AZURE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: azure-workload-identity-config
                  key: AZURE_CLIENT_ID
            - name: AZURE_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: azure-workload-identity-config
                  key: AZURE_TENANT_ID
            - name: AZURE_FEDERATED_TOKEN_FILE
              value: /var/run/secrets/azure/tokens/azure-identity-token
