apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio.yaml
  - otelcol.yaml
  - clickhouse.yaml
  - dice-service.yaml
  - grafana.yaml
  - hyperdx.yaml
  - dice-web.yaml
